services:
  postgres:
    image: postgres:12
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      postgres:
        condition: service_healthy      
    environment:
      POSTGRES_CONNECTION_STRING: postgres://postgres:postgres@postgres:5432/postgres
      AUTH_SYSTEM_ADMIN_USERNAME: admin
      AUTH_SYSTEM_ADMIN_PASSWORD: password

  frontend:
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      BOOKS_BACKEND_URL: http://server:3000